name: studio_foto
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  ticket_widget: ^0.0.1
  empty_widget: ^0.0.5
  ticket_material: ^0.3.1
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/paket/
# flutter_native_splash:
#   color: "#1a1a1a"
#   image: assets/images/logo_qm.jpg
#   android: true
#   ios: true
#   android_gravity: fill

#   android_12:
#     color: "#1a1a1a"
#     image: assets/images/logo_qm.jpg
#     android: true
#     ios: true
#     android_gravity: fill

#   web: false
